1|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/night.jpg
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/02.jpg
0|Decay-Green|~/.config/swww/Decay-Green/ok.jpg
0|Rose-Pine|~/.config/swww/Rose-Pine/yello.png
0|Tokyo-Night|~/.config/swww/Tokyo-Night/zer.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
0|Graphite-Mono|~/.config/swww/Graphite-Mono/rx-7.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/lucy.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/frost-white.png
